### ISSUE TITLE
I need v50 iOS ipa pls😭

### ISSUE THREAD

**Issue by LittleDuck-LD** [risporce/BSDS#1]
Why I cant find BSDS ipa on v50
Pls give me thx！！

**Comment by risporce** [comment]
Hi, the ipa is there on the v50 branch, the ipa is a mediafirelink in the readme file, the best way to access it so to switch branch in GitHub and select v50, the ipa link is there and working, I just tested it

**Comment by LittleDuck-LD** [comment]
OK，thx you too much😃
