### ISSUE TITLE
what do you do after

### ISSUE THREAD

**Issue by jackedoo612** [risporce/BSDS#6]
Listening for new connection...

**Comment by risporce** [comment]
the server is working, open the apk/ipa and play (make sure you have put the correct ip), if you host on computer, you have to put private ipv4 address of your pc in the client (instructions on the readme) . you can obtain that ip from network settings on your device
if you are playing on the same device as the one you run the server on, put the ip 127.0.0.1 in the client 

still facing issues?: come on the discord server (link on the readme) and provide pictures of server logs + tell us which server and client you use + screenshot of your config if android (don't worry, your private ipv4 is safe, we can't do anything with it, it's not the ip that an hacker can use)
